  deploy:
    name: Deploy to Mac mini
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Install cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb -o cf.deb
          sudo dpkg -i cf.deb
          cloudflared --version

      - name: Add SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_deploy
          chmod 600 ~/.ssh/id_deploy

      - name: Deploy over SSH via Cloudflare Tunnel
        env:
          GH_USER: ${{ github.repository_owner }}
          GHCR_READ_TOKEN: ${{ secrets.GHCR_READ_TOKEN }}
          COMPOSE_DIR: ${{ secrets.COMPOSE_PROJECT_DIR }}
        run: |
          set -e
          ssh -o "ProxyCommand cloudflared access ssh --hostname ssh.innakitchen.com" \
              -o BatchMode=yes -o StrictHostKeyChecking=no \
              -i ~/.ssh/id_deploy \
              korakod@ssh.innakitchen.com \
              "cd $COMPOSE_DIR && \
               docker login ghcr.io -u $GH_USER -p $GHCR_READ_TOKEN && \
               docker compose -f docker-compose.prod.yml pull && \
               docker compose -f docker-compose.prod.yml up -d && \
               docker image prune -f"
