name: CI/CD for my-web

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# ให้สิทธิ์ push/pull GHCR
permissions:
  contents: read
  packages: write
  id-token: write

# กันงานซ้อนกันตอน push ถี่ ๆ
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: E2E (Cypress via Docker Compose)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # รัน service "web" จาก docker-compose.yml
      - name: Start web via Compose
        run: docker compose up -d web

      # รอให้เว็บพร้อมตอบ (localhost:8080 บน GitHub runner)
      - name: Wait for web
        run: |
          for i in {1..30}; do
            if curl -fsS http://localhost:8080 >/dev/null; then
              echo "web is up"; exit 0
            fi
            echo "waiting..."; sleep 2
          done
          echo "web not responding"; exit 1

      # รันเทสต์ด้วย service "cypress" ใน compose (baseUrl=http://web)
      - name: Run Cypress (Docker)
        run: docker compose run --rm cypress

      - name: Show web logs if failed
        if: failure()
        run: docker logs my-web || true

      - name: Stop services
        if: always()
        run: docker compose down

  build_and_push:
    name: Build & Push to GHCR
    needs: test
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/my-web
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tags
        id: vars
        run: |
          echo "TAG=latest" >> $GITHUB_OUTPUT
          echo "SHA_TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.TAG }}
            ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.SHA_TAG }}

  deploy:
    name: Deploy to Mac mini
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy (docker compose pull/up)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}         # เช่น 192.168.x.x หรือโดเมน Tunnel
          username: ${{ secrets.SSH_USER }}     # เช่น korakod
          key: ${{ secrets.SSH_KEY }}           # private key (PEM)
          port: ${{ secrets.SSH_PORT }}         # ปกติ 22
          script: |
            set -e
            cd ${{ secrets.COMPOSE_PROJECT_DIR }}      # โฟลเดอร์ที่มี docker-compose.prod.yml
            docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GHCR_READ_TOKEN }}
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d
            docker image prune -f
